### PR TITLE
Proper colorization mechanics

### PR DESCRIPTION
**Pull request by krlvm**
Thank you for keeping my abandonware up and restoring my faith in that it can be done.

I've came up with a mechanism for the correct colorization of bitmaps without direct replacement of colors - this should work even on Windows Vista.

~~The only thing left with problems is with the highlighting of icons on the desktop and the buttons of the File Explorer toolbar~~.

I had to temporarily comment out the tray icon code because I accidentally broke it :/

### CODE REVIEW

**Comment by krlvm** [comment]
UPD: apparently there's no way to change File Explorer toolbar buttons highlight color without hooking into it

**Comment by rounk-ctrl** [comment]
Thank you!

**Comment by krlvm** [comment]
I made a [light variation](https://github.com/krlvm/AccentColorizer) without tray icon and additional functionality, please note the use of [DwmGetColorizationColor](https://github.com/krlvm/AccentColorizer/blob/master/AccentColorizer/AccentColorHelper.cpp) to get the accent color and [HSV hue caching](https://github.com/krlvm/AccentColorizer/blob/7b9ce4a16b870b68b5fc09dd3d565ef98127d830/AccentColorizer/StyleModifier.cpp#L13) to optimize performance if you are going to develop this program for finer work under Windows 10+.

**Comment by rounk-ctrl** [comment]
Do you know how to change the colors of control panel hyperlinks? 
these
image
Ig you would need hooking or something.

**Comment by krlvm** [comment]
I'm investigating further modifications to the in-memory theme, the hyperlink color is stored as a color value, not a bitmap, so no ideas yet. On the other hand, StartAllBack changes their color, but it also hooks into the explorer. It will probably be possible to do this with [GetThemeColor ](https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-getthemecolor)- it returns a COLORREF, unknown, a copy or a reference to the original one, you should try to replace its values.

**Comment by rounk-ctrl** [comment]
Well yeah I tried GetThemeColor but its last parameter is just a pointer to the COLORREF you want to store that value in.
so hooking it is.

**Pull request merged**
